
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Nav } from '../components/shared/Nav';
import '../sass/globals.sass';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Generica",
  description: "Generated by create next app",
};

export default function RootLayout({ children ,}: Readonly <{ children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
