
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { BarNav } from "@/components/shared/BarNav"





import 'bootstrap/dist/css/bootstrap.min.css'
import '../sass/globals.sass'



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Generica",
  description: "Generated by create next app",
};

export default function RootLayout({ children ,}: Readonly <{ children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BarNav />
        {children}
      </body>
    </html>
  );
}
