// Arrays de muebles

import { Furniture } from '@/types'

export const furnitureItems: Furniture[] = [
      {
            id: '1',
            name: 'Silla Moderna',
            description: 'Una silla moderna y cómoda con diseño ergonómico.',
            price: 120,
            imageUrl: '/categorias/living/sillon-blanco.webp',
            category: 'living',
          },
          {
            id: '2',
            name: 'Mesa de Centro',
            description: 'Mesa de centro de vidrio templado con patas de acero.',
            price: 300,
            imageUrl: '/images-main/comedor-1200.webp',
            category: 'living',
          },
          {
            id: '3',
            name: 'Sofá de Cuero',
            description: 'Sofá de cuero premium con capacidad para 3 personas.',
            price: 700,
            imageUrl: '/images-main/cocina-1200.webp',
            category: 'living',
          },
          {
            id: '4',
            name: 'Cama King Size',
            description: 'Cama King Size con cabecero de madera maciza.',
            price: 1200,
            imageUrl: '/images-main/relax-1200.webp',
            category: 'living',
          },
          {
            id: '5',
            name: 'Silla Moderna',
            description: 'Una silla moderna y cómoda con diseño ergonómico.',
            price: 120,
            imageUrl: '/categorias/living/sillon-blanco.webp',
            category: 'comedor',
          },
          {
            id: '6',
            name: 'Mesa de Centro',
            description: 'Mesa de centro de vidrio templado con patas de acero.',
            price: 300,
            imageUrl: '/images-main/comedor-1200.webp',
            category: 'comedor',
          },
          {
            id: '7',
            name: 'Sofá de Cuero',
            description: 'Sofá de cuero premium con capacidad para 3 personas.',
            price: 700,
            imageUrl: '/images-main/cocina-1200.webp',
            category: 'comedor',
          },
          {
            id: '8',
            name: 'Cama King Size',
            description: 'Cama King Size con cabecero de madera maciza.',
            price: 1200,
            imageUrl: '/images-main/relax-1200.webp',
            category: 'comedor',
          },
          {
            id: '9',
            name: 'Silla Moderna',
            description: 'Una silla moderna y cómoda con diseño ergonómico.',
            price: 120,
            imageUrl: '/categorias/living/sillon-blanco.webp',
            category: 'cocina',
          },
          {
            id: '10',
            name: 'Mesa de Centro',
            description: 'Mesa de centro de vidrio templado con patas de acero.',
            price: 300,
            imageUrl: '/images-main/comedor-1200.webp',
            category: 'cocina',
          },
          {
            id: '11',
            name: 'Sofá de Cuero',
            description: 'Sofá de cuero premium con capacidad para 3 personas.',
            price: 700,
            imageUrl: '/images-main/cocina-1200.webp',
            category: 'cocina',
          },
          {
            id: '12',
            name: 'Cama King Size',
            description: 'Cama King Size con cabecero de madera maciza.',
            price: 1200,
            imageUrl: '/images-main/relax-1200.webp',
            category: 'cocina',
          },
          {
            id: '13',
            name: 'Silla Moderna',
            description: 'Una silla moderna y cómoda con diseño ergonómico.',
            price: 120,
            imageUrl: '/categorias/living/sillon-blanco.webp',
            category: 'relax',
          },
          {
            id: '14',
            name: 'Mesa de Centro',
            description: 'Mesa de centro de vidrio templado con patas de acero.',
            price: 300,
            imageUrl: '/images-main/comedor-1200.webp',
            category: 'relax',
          },
          {
            id: '15',
            name: 'Sofá de Cuero',
            description: 'Sofá de cuero premium con capacidad para 3 personas.',
            price: 700,
            imageUrl: '/images-main/cocina-1200.webp',
            category: 'relax',
          },
          {
            id: '16',
            name: 'Cama King Size',
            description: 'Cama King Size con cabecero de madera maciza.',
            price: 1200,
            imageUrl: '/images-main/relax-1200.webp',
            category: 'relax',
          },
]